"""initial_schema

Revision ID: f950416317b9
Revises: 
Create Date: 2026-09-26 15:32:15.833999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f950416317b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_catalog',
    sa.Column('crop_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('typical_duration_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crop_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crop_catalog_crop_name'), ['crop_name'], unique=True)

    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=True),
    sa.Column('platform_role', sa.String(length=50), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_platform_role'), ['platform_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_verification_status'), ['verification_status'], unique=False)

    op.create_table('weather_advisories',
    sa.Column('region_code', sa.String(length=100), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_advisories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_advisories_data_type'), ['data_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_advisories_region_code'), ['region_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_weather_advisories_valid_until'), ['valid_until'], unique=False)

    op.create_table('admin_permission_grants',
    sa.Column('admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('permission_key', sa.String(length=100), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_permission_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_permission_grants_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_permission_grants_granted_by'), ['granted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_permission_grants_permission_key'), ['permission_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_permission_grants_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_permission_grants_revoked_by'), ['revoked_by'], unique=False)
        batch_op.create_index('ix_admin_permission_grants_user_perm', ['admin_user_id', 'permission_key'], unique=False)

    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('metadata_redacted', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)

    op.create_table('farmer_verifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('selfie_photo_key', sa.String(length=500), nullable=False),
    sa.Column('land_photo_key', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('docs_purge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farmer_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_verifications_docs_purge_at'), ['docs_purge_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_farmer_verifications_reviewed_by'), ['reviewed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_farmer_verifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_farmer_verifications_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_farmer_verifications_user_id'), ['user_id'], unique=False)

    op.create_table('farms',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('soil_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farms_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_family', sa.String(length=100), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_is_revoked'), ['is_revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_family'), ['token_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('plots',
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('plot_name', sa.String(length=255), nullable=False),
    sa.Column('area_acres', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plots_farm_id'), ['farm_id'], unique=False)

    op.create_table('crop_cycles',
    sa.Column('plot_id', sa.Uuid(), nullable=False),
    sa.Column('crop_catalog_id', sa.Uuid(), nullable=False),
    sa.Column('sowing_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('actual_harvest_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crop_catalog_id'], ['crop_catalog.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crop_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crop_cycles_crop_catalog_id'), ['crop_catalog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crop_cycles_plot_id'), ['plot_id'], unique=False)
        batch_op.create_index('ix_crop_cycles_plot_id_status', ['plot_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_crop_cycles_status'), ['status'], unique=False)

    op.create_table('farm_activities',
    sa.Column('crop_cycle_id', sa.Uuid(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farm_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farm_activities_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_farm_activities_crop_cycle_id'), ['crop_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_farm_activities_scheduled_date'), ['scheduled_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farm_activities_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_farm_activities_crop_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_farm_activities_activity_type'))

    op.drop_table('farm_activities')
    with op.batch_alter_table('crop_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crop_cycles_status'))
        batch_op.drop_index('ix_crop_cycles_plot_id_status')
        batch_op.drop_index(batch_op.f('ix_crop_cycles_plot_id'))
        batch_op.drop_index(batch_op.f('ix_crop_cycles_crop_catalog_id'))

    op.drop_table('crop_cycles')
    with op.batch_alter_table('plots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plots_farm_id'))

    op.drop_table('plots')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_family'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_is_revoked'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_expires_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farms_user_id'))

    op.drop_table('farms')
    with op.batch_alter_table('farmer_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_verifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_farmer_verifications_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_farmer_verifications_status'))
        batch_op.drop_index(batch_op.f('ix_farmer_verifications_reviewed_by'))
        batch_op.drop_index(batch_op.f('ix_farmer_verifications_docs_purge_at'))

    op.drop_table('farmer_verifications')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('admin_permission_grants', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_permission_grants_user_perm')
        batch_op.drop_index(batch_op.f('ix_admin_permission_grants_revoked_by'))
        batch_op.drop_index(batch_op.f('ix_admin_permission_grants_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_admin_permission_grants_permission_key'))
        batch_op.drop_index(batch_op.f('ix_admin_permission_grants_granted_by'))
        batch_op.drop_index(batch_op.f('ix_admin_permission_grants_admin_user_id'))

    op.drop_table('admin_permission_grants')
    with op.batch_alter_table('weather_advisories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_advisories_valid_until'))
        batch_op.drop_index(batch_op.f('ix_weather_advisories_region_code'))
        batch_op.drop_index(batch_op.f('ix_weather_advisories_data_type'))

    op.drop_table('weather_advisories')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_verification_status'))
        batch_op.drop_index(batch_op.f('ix_users_platform_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('crop_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crop_catalog_crop_name'))

    op.drop_table('crop_catalog')
    # ### end Alembic commands ###
